### ISSUE TITLE
[BUG] Build error: node version & useless dependence

### ISSUE THREAD

**Issue by lixworth** [UniiemStudio/CTFever#65]
**描述问题**
* node lts 18 build faild
* useless dependence `vue-jest` 造成 #59 中需安装gcc与python环境
* 项目不应同时存在 package lock 与 yarn lock

**复现问题**
详细写出复现问题的步骤
1. Launch Genshin Impack
2. Click Play Button

**预期表现**
简单描述你认为正确的表现

**截图**
![image](https://user-images.githubusercontent.com/22554300/208267431-c799346d-399c-4896-b30e-2c68278f68db.png)
![image](https://user-images.githubusercontent.com/22554300/208267443-fed136b8-d63f-4308-b75a-f289e2db3dd5.png)

**环境**
 - 操作系统: [e.g. Windows11]
 - 浏览器: [e.g. chrome, safari]
 - 版本号: [e.g. 100]

**Comment by HoshinoSuzumi** [comment]
use Node <= 16 plz
