### ISSUE TITLE
[BUG]本地部署报错

### ISSUE THREAD

**Issue by Xc1Ym** [UniiemStudio/CTFever#76]
**Describe the bug**
本地部署出现错误

**描述问题**
简单的描述你所遇到的问题

**复现问题**
详细写出复现问题的步骤
1. 执行`yarn dev`后报错`Error: error:0308010C:digital envelope routines::unsupported`

**截图**

![image](https://user-images.githubusercontent.com/29765332/233259350-f3840cc6-529e-4dc0-84bb-b5d83de83025.png)

**环境**
 - 操作系统: Ubuntu 22.04.2 LTS
 - node.js v18.16.0

**Comment by HoshinoSuzumi** [comment]
这个问题出现在新版本 Node(v18) 您可以尝试降级到 Node(v16 LTS) 或者使用旧版 OpenSSL
`"start": "react-scripts --openssl-legacy-provider start"`

**Comment by Xc1Ym** [comment]
感谢，已经部署好了
