### ISSUE TITLE
[FEAT] 集成CyberChef

### ISSUE THREAD

**Issue by ciaoly** [UniiemStudio/CTFever#77]
**描述你的诉求**
加解密和编解码有CaptfEncoder和CyberChef了, 与其再做几个加解密进去, 不如直接集成cyberchef. 另外, [kt.gy tools](https://kt.gy/tools.html#conv/) 这个解码工具挺好用的, 不知道可不可以集成进去?

**Comment by HoshinoSuzumi** [comment]
首先感谢您的建议！直接集成 CyberChef 或者其他工具可能存在一些不妥。

不过**值得庆幸的是**我们正在创建一个类似 kt.gy 的聚合编解码工具，并将会在近期推出。
