### ISSUE TITLE
[BUG]本地使用docker部署时, 端口扫描不可用

### ISSUE THREAD

**Issue by cachexy123** [UniiemStudio/CTFever#86]
出现Unknown error错误, 是否docker中需要执行其他命令?

**Comment by HoshinoSuzumi** [comment]
请用打开浏览器控制台并再次尝试，检查并提供报错信息。值得一提的是即便是在本地部署，带黄色点标的工具仍然需要网络请求后端接口。

**Comment by cachexy123** [comment]
https://xxx.xx.com/gateway/call/portscan?method=scan 状态码405

**Comment by cachexy123** [comment]
我大概知道原因了

**Comment by cachexy123** [comment]
不对, 仍然无法网络请求后端接口, 是不是docker的问题, 我试试其他部署方法

**Comment by cachexy123** [comment]
该如何修改后端地址?

**Comment by HoshinoSuzumi** [comment]
> 该如何修改后端地址?

https://github.com/UniiemStudio/CTFever/blob/6726b955cb9af6e8181cadea3a59e8a6f508b8cd/nuxt.config.js#L189

**Comment by HoshinoSuzumi** [comment]
经过检查，发现这是一个历史遗留问题。目前 main 分支使用 proxy 代理后端接口，但 docker 镜像仍然使用 nginx 直接提供静态服务。这个问题最近将被修复 (参见 #80)。请等待我们修复。

**Comment by cachexy123** [comment]
okay

**Comment by HoshinoSuzumi** [comment]
该问题已经修复 #80
